In [ ]:
import numpy as np
import pandas as pd
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

from sklearn import metrics

In [ ]:
data = pd.read_csv('/content/445.csv')
data = data.sample(frac = 1)
data.isnull().sum()
data.drop('user', inplace=True, axis=1)


In [ ]:
print(data)

         activity     timestamp  x-axis  y-axis  z-axis
52610     Walking  5.300000e+12   -2.18    1.38   -0.72
11464  Downstairs  6.760000e+12    3.91    8.62    0.00
20481     Jogging  5.400000e+12  -14.48  -13.21    3.30
4674     Standing  5.900000e+13    2.15    9.43    2.56
33054     Sitting  2.090000e+14   -6.13   -3.41    7.08
...           ...           ...     ...     ...     ...
13076  Downstairs  1.030000e+14    9.28    4.60    2.41
33138     Sitting  2.090000e+14   -6.44   -3.57    6.78
26535     Sitting  1.020000e+14    1.42    0.27    9.66
35049     Sitting  2.090000e+14   -6.63   -3.26    6.78
42753    Upstairs  1.030000e+14   -1.42   -0.76   -1.46

[59994 rows x 5 columns]


In [ ]:
data_dup = data.duplicated().any()
data = data.drop_duplicates()
print(data_dup)

True


In [ ]:
categorical=[]
numerical=[]


for column in data.columns:
  if data[column].nunique()<=10 :
    categorical.append(column)
  else:
    numerical.append(column)





In [ ]:
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()
data['activity_cat'] = LE.fit_transform(data['activity'])



<ipython-input-270-48244c6bce6a>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['activity_cat'] = LE.fit_transform(data['activity'])


In [ ]:
data['activity'].unique()
data = pd.get_dummies(data,columns = categorical,drop_first = True)
data.head()

timestamp  x-axis  y-axis  z-axis  activity_cat  activity_Jogging  \
52610  5.300000e+12   -2.18    1.38   -0.72             5                 0   
11464  6.760000e+12    3.91    8.62    0.00             0                 0   
20481  5.400000e+12  -14.48  -13.21    3.30             1                 1   
4674   5.900000e+13    2.15    9.43    2.56             3                 0   
33054  2.090000e+14   -6.13   -3.41    7.08             2                 0   

       activity_Sitting  activity_Standing  activity_Upstairs  \
52610                 0                  0                  0   
11464                 0                  0                  0   
20481                 0                  0                  0   
4674                  0                  1                  0   
33054                 1                  0                  0   

       activity_Walking  
52610                 1  
11464                 0  
20481                 0  
4674                  0  
33054                 0

In [ ]:
data

timestamp  x-axis  y-axis    z-axis  activity_cat  activity_Jogging  \
52610  5.300000e+12   -2.18    1.38 -0.720000             5                 0   
11464  6.760000e+12    3.91    8.62  0.000000             0                 0   
20481  5.400000e+12  -14.48  -13.21  3.300000             1                 1   
4674   5.900000e+13    2.15    9.43  2.560000             3                 0   
33054  2.090000e+14   -6.13   -3.41  7.080000             2                 0   
...             ...     ...     ...       ...           ...               ...   
38461  6.730000e+12   -6.97   -5.33  4.060000             4                 0   
3302   3.170000e+12   -1.46    9.58  0.953424             3                 0   
13076  1.030000e+14    9.28    4.60  2.410000             0                 0   
33138  2.090000e+14   -6.44   -3.57  6.780000             2                 0   
42753  1.030000e+14   -1.42   -0.76 -1.460000             4                 0   

       activity_Sitting  activity_Standing  activity_Upstairs  \
52610                 0                  0                  0   
11464                 0                  0                  0   
20481                 0                  0                  0   
4674                  0                  1                  0   
33054                 1                  0                  0   
...                 ...                ...                ...   
38461                 0                  0                  1   
3302                  0                  1                  0   
13076                 0                  0                  0   
33138                 1                  0                  0   
42753                 0                  0                  1   

       activity_Walking  
52610                 1  
11464                 0  
20481                 0  
4674                  0  
33054                 0  
...                 ...  
38461                 0  
3302                  0  
13076                 0  
33138                 0  
42753                 0  

[40401 rows x 10 columns]

In [ ]:

X = data.drop(['activity_cat','activity_Jogging','activity_Sitting','activity_Standing','activity_Upstairs','activity_Walking'] , axis = 1)
y = data['activity_cat']

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3,random_state = 42)



In [ ]:
print(X)

          timestamp  x-axis  y-axis    z-axis
52610  5.300000e+12   -2.18    1.38 -0.720000
11464  6.760000e+12    3.91    8.62  0.000000
20481  5.400000e+12  -14.48  -13.21  3.300000
4674   5.900000e+13    2.15    9.43  2.560000
33054  2.090000e+14   -6.13   -3.41  7.080000
...             ...     ...     ...       ...
38461  6.730000e+12   -6.97   -5.33  4.060000
3302   3.170000e+12   -1.46    9.58  0.953424
13076  1.030000e+14    9.28    4.60  2.410000
33138  2.090000e+14   -6.44   -3.57  6.780000
42753  1.030000e+14   -1.42   -0.76 -1.460000

[40401 rows x 4 columns]


In [ ]:
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler()
df_min_max_scale = data.copy()
for column in data.columns:
  data[column] = (df_min_max_scale[column] - df_min_max_scale[column].min())/(df_min_max_scale[column].max()-df_min_max_scale.min())

In [ ]:
from sklearn.preprocessing import StandardScaler
st = StandardScaler()
st.fit(X_train)
X_train = st.fit_transform(X_train)
X_test = st.fit_transform(X_test)


In [ ]:
print(X_train)

[[-0.66608954 -2.55298178 -0.01761655 -0.74808892]
 [-0.69548085  0.280289    0.61027749 -0.21163715]
 [ 0.8516841  -0.87394951  1.07437308  0.86595155]
 ...
 [ 0.8516841   1.07132712 -0.27241413  0.39743473]
 [-0.66515648  1.34372741 -2.39876061 -0.68718173]
 [-0.66453444  1.77926007 -3.85171348  0.71368358]]


In [ ]:
print(X_test)

[[-0.63884365 -2.34619061 -1.12146243  0.41463149]
 [ 0.16372989  1.18067909 -0.56401225  1.28569929]
 [-0.63930526 -0.4041221  -0.88276701 -1.27833094]
 ...
 [-0.66530889  2.38531121  1.34406853  0.9789523 ]
 [-0.68608102 -1.27133508 -1.0636418  -1.5663453 ]
 [ 0.99615376 -0.70947878  0.198034    0.10320133]]


In [ ]:
y_train = y_train.astype(int)
y_test = y_test.astype(int)


**Logistic Regression**

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,classification_report 

LR = LogisticRegression()
LR.fit(X_train,y_train.ravel())
pred = LR.predict(X_test)
print(accuracy_score(y_test,pred))
print(classification_report(y_test,pred))

0.49896873195280916
              precision    recall  f1-score   support

           0       0.34      0.28      0.31      2927
           1       0.62      0.65      0.63       971
           2       0.70      0.74      0.72      1284
           3       0.64      0.69      0.67      2099
           4       0.37      0.30      0.33      2863
           5       0.49      0.66      0.56      1977

    accuracy                           0.50     12121
   macro avg       0.53      0.56      0.54     12121
weighted avg       0.48      0.50      0.49     12121



**KNN**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier 
k_range = range(1,50)
score=[]

for k in k_range:
  knn_classifier= KNeighborsClassifier(n_neighbors=k, metric='minkowski', p=2 )  
  knn_classifier.fit(X_train, y_train) 
  y_pred = knn_classifier.predict(X_test)
  acc_score = accuracy_score(y_test,y_pred)
  score.append(acc_score)

print(score)  

In [ ]:
import matplotlib.pyplot as plt

%matplotlib inline


plt.plot(k_range, score)
plt.xlabel('Value of K for KNN')
plt.ylabel('Testing Accuracy')

In [ ]:
from sklearn import metrics

print(metrics.accuracy_score(y_test, y_pred))
print(classification_report(y_test,y_pred))
X_new = [['4.03E+12','3.79','10.46','-0.76']]
print(knn_classifier.predict(X_new))


**SVM**

In [ ]:
from sklearn  import svm
model = svm.SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
acc = accuracy_score(y_test,y_pred)
print(acc)

0.7017572807524132


**NaiveBayes**

In [ ]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)

GaussianNB()

In [ ]:
y_pred = gnb.predict(X_test)
y_pred

array([4, 0, 4, ..., 1, 4, 3])

In [ ]:
from sklearn.metrics import accuracy_score
print('Model accuracy score: {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy score: 0.4132


In [ ]:
y_pred_train = gnb.predict(X_train)
y_pred_train
print('Training-set accuracy score: {0:0.4f}'. format(accuracy_score(y_train, y_pred_train)))

Training-set accuracy score: 0.6604


In [ ]:
print('Training set score: {:.4f}'.format(gnb.score(X_train, y_train)))
print('Test set score: {:.4f}'.format(gnb.score(X_test, y_test)))
print(print(classification_report(y_test,y_pred)))

Training set score: 0.6604
Test set score: 0.4132
              precision    recall  f1-score   support

           0       0.37      0.63      0.47      2927
           1       0.00      0.00      0.00       971
           2       0.54      0.49      0.51      1284
           3       0.71      0.75      0.73      2099
           4       0.35      0.33      0.34      2863
           5       1.00      0.00      0.00      1977

    accuracy                           0.41     12121
   macro avg       0.49      0.37      0.34     12121
weighted avg       0.51      0.41      0.37     12121

None


In [ ]:
RFclassifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 42)
RFclassifier.fit(X_train, y_train)
y_pred = RFclassifier.predict(X_test)
print(accuracy_score(y_test,y_pred))

0.5962379341638478
