In [94]:
import numpy as np
import pandas as pd
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score

In [95]:
from google.colab import drive
drive.mount('/content/drive/')


Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [96]:
data = pd.read_csv('/content/445.csv')
data = data.sample(frac = 1)
data.isnull().sum()
data.drop('user', inplace=True, axis=1)


In [97]:
print(data)

         activity     timestamp  x-axis  y-axis    z-axis
13464  Downstairs  1.030000e+14    2.37    7.27 -5.050000
18057  Downstairs  2.580000e+12    0.00   13.21  4.794363
53120     Walking  5.330000e+12   -3.72   15.28  0.230000
24031     Jogging  5.420000e+12    1.88    3.95 -1.880000
39701    Upstairs  1.030000e+14   -0.50   -3.02 -2.070000
...           ...           ...     ...     ...       ...
36051     Sitting  1.120000e+14   -0.89   -1.73  9.470000
22126     Jogging  5.480000e+12   10.80    3.83  0.930000
13904  Downstairs  1.030000e+14   -1.27   11.80  5.560000
33858     Sitting  2.090000e+14   -6.59   -3.26  6.740000
1031     Standing  1.030000e+14   -1.12    9.38 -0.500000

[59994 rows x 5 columns]


In [98]:
data_dup = data.duplicated().any()
data = data.drop_duplicates()
print(data_dup)

True


In [99]:
categorical=[]
numerical=[]


for column in data.columns:
  if data[column].nunique()<=10 :
    categorical.append(column)
  else:
    numerical.append(column)





In [100]:
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()
data['activity_cat'] = LE.fit_transform(data['activity'])



In [101]:
data['activity'].unique()
data = pd.get_dummies(data,columns = categorical,drop_first = True)
data.head()

timestamp  x-axis  y-axis    z-axis  activity_cat  activity_Jogging  \
13464  1.030000e+14    2.37    7.27 -5.050000             0                 0   
18057  2.580000e+12    0.00   13.21  4.794363             0                 0   
53120  5.330000e+12   -3.72   15.28  0.230000             5                 0   
24031  5.420000e+12    1.88    3.95 -1.880000             1                 1   
39701  1.030000e+14   -0.50   -3.02 -2.070000             4                 0   

       activity_Sitting  activity_Standing  activity_Upstairs  \
13464                 0                  0                  0   
18057                 0                  0                  0   
53120                 0                  0                  0   
24031                 0                  0                  0   
39701                 0                  0                  1   

       activity_Walking  
13464                 0  
18057                 0  
53120                 1  
24031                 0  
39701                 0

In [102]:
data

timestamp  x-axis  y-axis    z-axis  activity_cat  activity_Jogging  \
13464  1.030000e+14    2.37    7.27 -5.050000             0                 0   
18057  2.580000e+12    0.00   13.21  4.794363             0                 0   
53120  5.330000e+12   -3.72   15.28  0.230000             5                 0   
24031  5.420000e+12    1.88    3.95 -1.880000             1                 1   
39701  1.030000e+14   -0.50   -3.02 -2.070000             4                 0   
...             ...     ...     ...       ...           ...               ...   
15765  1.030000e+14   -2.79   10.19  1.310000             0                 0   
34706  2.090000e+14   -6.66   -3.06  6.700000             2                 0   
3838   3.200000e+12   -1.73    9.58  0.721878             3                 0   
6099   2.090000e+14   -8.12    5.60 -0.650000             3                 0   
13904  1.030000e+14   -1.27   11.80  5.560000             0                 0   

       activity_Sitting  activity_Standing  activity_Upstairs  \
13464                 0                  0                  0   
18057                 0                  0                  0   
53120                 0                  0                  0   
24031                 0                  0                  0   
39701                 0                  0                  1   
...                 ...                ...                ...   
15765                 0                  0                  0   
34706                 1                  0                  0   
3838                  0                  1                  0   
6099                  0                  1                  0   
13904                 0                  0                  0   

       activity_Walking  
13464                 0  
18057                 0  
53120                 1  
24031                 0  
39701                 0  
...                 ...  
15765                 0  
34706                 0  
3838                  0  
6099                  0  
13904                 0  

[40401 rows x 10 columns]

In [103]:

X = data.drop(['activity_cat','activity_Jogging','activity_Sitting','activity_Standing','activity_Upstairs','activity_Walking'] , axis = 1)
y = data['activity_cat']
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3,random_state = 42)



In [104]:
print(X)

          timestamp  x-axis  y-axis    z-axis
13464  1.030000e+14    2.37    7.27 -5.050000
18057  2.580000e+12    0.00   13.21  4.794363
53120  5.330000e+12   -3.72   15.28  0.230000
24031  5.420000e+12    1.88    3.95 -1.880000
39701  1.030000e+14   -0.50   -3.02 -2.070000
...             ...     ...     ...       ...
15765  1.030000e+14   -2.79   10.19  1.310000
34706  2.090000e+14   -6.66   -3.06  6.700000
3838   3.200000e+12   -1.73    9.58  0.721878
6099   2.090000e+14   -8.12    5.60 -0.650000
13904  1.030000e+14   -1.27   11.80  5.560000

[40401 rows x 4 columns]


In [105]:
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler()
df_min_max_scale = data.copy()
for column in data.columns:
  data[column] = (df_min_max_scale[column] - df_min_max_scale[column].min())/(df_min_max_scale[column].max()-df_min_max_scale.min())

In [106]:
from sklearn.preprocessing import StandardScaler
st = StandardScaler()
st.fit(X_train)
X_train = st.fit_transform(X_train)
X_test = st.fit_transform(X_test)


In [107]:
print(X_train)

[[-0.69475605 -0.96923084  1.20736846 -0.53468858]
 [-0.70868871  0.3830072   1.42095893 -0.29227038]
 [-0.69227913  0.02771929  0.52748893 -0.65831004]
 ...
 [ 0.83210848  0.42588677 -0.96012356  2.01471233]
 [-0.66286574  0.45498363  1.54730822  2.01471233]
 [-0.66317536 -0.65988533  0.29133609  1.74414462]]


In [108]:
print(X_test)

[[-0.67158967  0.46237367  0.58425802 -0.99557719]
 [-0.66863534 -1.01878424 -0.68281573 -0.87965947]
 [-0.66521454 -1.1068197  -0.99543106  0.93953896]
 ...
 [ 0.8517551   0.0221964   0.42719524 -0.28114555]
 [-0.70797455  0.37124925 -0.17840258  0.23443558]
 [-0.66614748  1.28558239 -0.06966681  2.69013303]]


In [109]:
y_train = y_train.astype(int)
y_test = y_test.astype(int)


In [110]:
from sklearn  import svm

model = svm.SVC()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
acc = accuracy_score(y_test,y_pred)
print(acc)

0.6950746638066166


In [111]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,classification_report 

LR = LogisticRegression()
LR.fit(X_train,y_train.ravel())
pred = LR.predict(X_test)
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.34      0.26      0.30      2988
           1       0.61      0.64      0.63       918
           2       0.70      0.80      0.74      1269
           3       0.62      0.69      0.65      2068
           4       0.36      0.30      0.33      2867
           5       0.50      0.68      0.58      2011

    accuracy                           0.50     12121
   macro avg       0.52      0.56      0.54     12121
weighted avg       0.48      0.50      0.48     12121

